from typing import Any, Callable, Dict, List, Optional, Union, Tuple, Type

class AI:
    def __init__(self: Any, driver_name: Any, api_key: Any, base_url: Any) -> Any: ...
    def free(self: Any) -> Any: ...
    def __del__(self: Any) -> Any: ...
    @staticmethod
    def get_stats() -> Any: ...
    @staticmethod
    def register_monitor(ctx: Any) -> Any: ...
    def chat(self: Any, model: Any, messages: Any, temperature: Any, max_tokens: Any, on_chunk: Any, timeout_ms: Any) -> Any: ...
    def generate_embeddings(self: Any, model: Any, input_texts: Any) -> Any: ...

class AIContext:
    def __init__(self: Any, max_history: Any) -> Any: ...
    def free(self: Any) -> Any: ...
    def __del__(self: Any) -> Any: ...
    def add(self: Any, role: Any, content: Any) -> Any: ...
    def clear(self: Any) -> Any: ...
    @property
    def count(self: Any) -> Any: ...
    @property
    def messages(self: Any) -> Any: ...
