from typing import Any, Callable, Dict, List, Optional, Union, Tuple, Type

from csilk.context import Context
class App:
    def __init__(self: Any, config_path: Any) -> Any: ...
    def free(self: Any) -> Any: ...
    def exception_handler(self: Any, exc_class: Any) -> Any: ...
    def _handle_exception(self: Any, ctx: Any, exc: Any) -> Any: ...
    def route(self: Any, method: Any, path: Any, handler: Any, input_type: Any, output_type: Any, summary: Any, description: Any, perm_required: Any, perm_resource: Any) -> Any: ...
    def get(self: Any, path: Any, handler: Any, **kwargs: Any) -> Any: ...
    def post(self: Any, path: Any, handler: Any, **kwargs: Any) -> Any: ...
    def put(self: Any, path: Any, handler: Any, **kwargs: Any) -> Any: ...
    def delete(self: Any, path: Any, handler: Any, **kwargs: Any) -> Any: ...
    def patch(self: Any, path: Any, handler: Any, **kwargs: Any) -> Any: ...
    def options(self: Any, path: Any, handler: Any, **kwargs: Any) -> Any: ...
    def head(self: Any, path: Any, handler: Any, **kwargs: Any) -> Any: ...
    def log_level(self: Any, level: Any) -> Any: ...
    def log_file(self: Any, path: Any, max_sz: Any) -> Any: ...
    def log_json(self: Any, enable: Any) -> Any: ...
    def static(self: Any, prefix: Any, root_dir: Any) -> Any: ...
    def enable_openapi(self: Any, enable: Any) -> Any: ...
    def use(self: Any, handler: Any) -> Any: ...
    def use_group(self: Any, prefix: Any, handler: Any) -> Any: ...
    def apply_config(self: Any) -> Any: ...
    def set_server_config(self: Any, idle_timeout_ms: Any, read_timeout_ms: Any, write_timeout_ms: Any, request_timeout_ms: Any, max_body_size: Any, max_header_size: Any, max_url_size: Any, max_headers_count: Any, max_connections: Any, listen_backlog: Any, tcp_nodelay: Any, tcp_keepalive: Any, worker_threads: Any, enable_tls: Any, tls_cert_file: Any, tls_key_file: Any, tls_ca_file: Any, tls_verify_peer: Any, h2_push_enable: Any, h2_max_push_per_request: Any, enable_simd: Any, enable_arena_alignment: Any, enable_openapi: Any) -> Any: ...
    @property
    def mq(self: Any) -> Any: ...
    def admin_serve(self: Any, path: Any) -> Any: ...
    def admin_serve_secure(self: Any, path: Any, auth_middleware: Any) -> Any: ...
    def run(self: Any, port: Any) -> Any: ...
    def stop(self: Any) -> Any: ...
    def on_server_start(self: Any, callback: Any) -> Any: ...
    def on_server_stop(self: Any, callback: Any) -> Any: ...
    def on_conn_open(self: Any, callback: Any) -> Any: ...
    def on_conn_close(self: Any, callback: Any) -> Any: ...
    def on_request_begin(self: Any, callback: Any) -> Any: ...
    def on_request_end(self: Any, callback: Any) -> Any: ...
    def _register_hook(self: Any, hook_type: Any, callback: Any, server_level: Any) -> Any: ...
    def set_not_found_handler(self: Any, handler: Any) -> Any: ...
    def set_spa_fallback(self: Any, doc_root: Any) -> Any: ...
    def set_max_connections(self: Any, max_conn: Any) -> Any: ...
    @property
    def server_stats(self: Any) -> Any: ...
    def __del__(self: Any) -> Any: ...
    def group(self: Any, prefix: Any) -> Any: ...

def recovery_middleware(ctx: Any) -> Any: ...

def logger_middleware(ctx: Any) -> Any: ...

def waf_middleware(ctx: Any) -> Any: ...

def request_id_middleware(ctx: Any) -> Any: ...

def health_check_handler(ctx: Any) -> Any: ...

def ready_check_handler(ctx: Any) -> Any: ...

def csrf_middleware(ctx: Any) -> Any: ...

def gzip_middleware(ctx: Any) -> Any: ...

def rate_limit(limit: Any) -> Any: ...

def cors(allow_origin: Any, allow_methods: Any, allow_headers: Any, allow_credentials: Any, max_age: Any) -> Any: ...

def jwt_middleware(secret: Any) -> Any: ...

class MqContext:
    def __init__(self: Any, ctx_ptr: Any) -> Any: ...
    @property
    def topic(self: Any) -> Any: ...
    @property
    def payload(self: Any) -> Any: ...
    def next(self: Any) -> Any: ...
    def abort(self: Any) -> Any: ...

class MQ:
    def __init__(self: Any, mq_ptr: Any) -> Any: ...
    def subscribe(self: Any, topic: Any, handler: Any) -> Any: ...
    def use(self: Any, topic: Any, handler: Any) -> Any: ...
    def publish(self: Any, topic: Any, payload: Any) -> Any: ...
    def set_persistence(self: Any, wal_path: Any) -> Any: ...
    @property
    def stats(self: Any) -> Any: ...

class Group:
    def __init__(self: Any, app: Any, prefix: Any, group_ptr: Any, parent: Any) -> Any: ...
    def free(self: Any) -> Any: ...
    def __del__(self: Any) -> Any: ...
    def use(self: Any, middleware: Any) -> Any: ...
    def route(self: Any, method: Any, path: Any, handler: Any, input_type: Any, output_type: Any, summary: Any, description: Any, perm_required: Any, perm_resource: Any) -> Any: ...
    def get(self: Any, path: Any, handler: Any, **kwargs: Any) -> Any: ...
    def post(self: Any, path: Any, handler: Any, **kwargs: Any) -> Any: ...
    def put(self: Any, path: Any, handler: Any, **kwargs: Any) -> Any: ...
    def delete(self: Any, path: Any, handler: Any, **kwargs: Any) -> Any: ...
    def patch(self: Any, path: Any, handler: Any, **kwargs: Any) -> Any: ...
    def options(self: Any, path: Any, handler: Any, **kwargs: Any) -> Any: ...
    def head(self: Any, path: Any, handler: Any, **kwargs: Any) -> Any: ...
    def group(self: Any, prefix: Any) -> Any: ...
