from typing import Any, Callable, Dict, List, Optional, Union, Tuple, Type

class Session:
    def __init__(self: Any, ctx: Any) -> Any: ...
    @property
    def id(self: Any) -> Any: ...
    def _prune(self: Any) -> Any: ...
    def __getitem__(self: Any, key: Any) -> Any: ...
    def __setitem__(self: Any, key: Any, value: Any) -> Any: ...
    def __delitem__(self: Any, key: Any) -> Any: ...
    def __contains__(self: Any, key: Any) -> Any: ...
    def get(self: Any, key: Any, default: Any) -> Any: ...
    def pop(self: Any, key: Any, default: Any) -> Any: ...
    def clear(self: Any) -> Any: ...

class CaseInsensitiveDict:
    def __init__(self: Any, data: Any, **kwargs: Any) -> Any: ...
    def __setitem__(self: Any, key: Any, value: Any) -> Any: ...
    def __getitem__(self: Any, key: Any) -> Any: ...
    def __delitem__(self: Any, key: Any) -> Any: ...
    def __contains__(self: Any, key: Any) -> Any: ...
    def get(self: Any, key: Any, default: Any) -> Any: ...
    def update(self: Any, E: Any, **F: Any) -> Any: ...
    def pop(self: Any, key: Any, default: Any) -> Any: ...

class Context:
    def __init__(self: Any, ctx_ptr: Any) -> Any: ...
    @property
    def method(self: Any) -> Any: ...
    @property
    def path(self: Any) -> Any: ...
    @property
    def body(self: Any) -> Any: ...
    @property
    def body_len(self: Any) -> Any: ...
    @property
    def is_websocket(self: Any) -> Any: ...
    @property
    def is_sse(self: Any) -> Any: ...
    @property
    def is_async(self: Any) -> Any: ...
    def is_async(self: Any, val: Any) -> Any: ...
    @property
    def is_aborted(self: Any) -> Any: ...
    @property
    def request_id(self: Any) -> Any: ...
    def request_id(self: Any, val: Any) -> Any: ...
    @property
    def status_code(self: Any) -> Any: ...
    def status_code(self: Any, val: Any) -> Any: ...
    def query(self: Any, key: Any) -> Any: ...
    def param(self: Any, key: Any) -> Any: ...
    @property
    def params(self: Any) -> Any: ...
    def get_header(self: Any, key: Any) -> Any: ...
    def get_response_header(self: Any, key: Any) -> Any: ...
    def set_request_header(self: Any, key: Any, value: Any) -> Any: ...
    def status(self: Any, code: Any) -> Any: ...
    def string(self: Any, code: Any, text: Any) -> Any: ...
    def json(self: Any, code: Any, data: Any) -> Any: ...
    def json_error(self: Any, code: Any, message: Any) -> Any: ...
    def set_header(self: Any, key: Any, value: Any) -> Any: ...
    def add_header(self: Any, key: Any, value: Any) -> Any: ...
    def file(self: Any, path: Any) -> Any: ...
    def redirect(self: Any, code: Any, location: Any) -> Any: ...
    def redirect_simple(self: Any, location: Any) -> Any: ...
    def next(self: Any) -> Any: ...
    def abort(self: Any) -> Any: ...
    def ws_handshake(self: Any) -> Any: ...
    def set_on_ws_message(self: Any, callback: Any) -> Any: ...
    def ws_send(self: Any, payload: Any, opcode: Any) -> Any: ...
    def ws_close(self: Any, status_code: Any, reason: Any) -> Any: ...
    def ws_join_room(self: Any, room_name: Any) -> Any: ...
    def ws_leave_room(self: Any, room_name: Any) -> Any: ...
    def ws_broadcast_room(self: Any, room_name: Any, message: Any) -> Any: ...
    def sse_init(self: Any) -> Any: ...
    def sse_send(self: Any, event: Any, data: Any) -> Any: ...
    def sse_close(self: Any) -> Any: ...
    def response_write(self: Any, data: Any) -> Any: ...
    def response_end(self: Any) -> Any: ...
    def push_promise(self: Any, method: Any, path: Any) -> Any: ...
    def get_cookie(self: Any, name: Any) -> Any: ...
    def set_cookie(self: Any, name: Any, value: Any, max_age: Any, path: Any, domain: Any, secure: Any, http_only: Any) -> Any: ...
    def parse_form_urlencoded(self: Any) -> Any: ...
    @property
    def headers(self: Any) -> Any: ...
    @property
    def queries(self: Any) -> Any: ...
    @property
    def form_fields(self: Any) -> Any: ...
    @property
    def handler_path(self: Any) -> Any: ...
    @property
    def handler_perm_required(self: Any) -> Any: ...
    @property
    def handler_perm_resource(self: Any) -> Any: ...
    def set_string(self: Any, key: Any, value: Any, ttl_sec: Any) -> Any: ...
    def get_string(self: Any, key: Any) -> Any: ...
    def incr(self: Any, key: Any, ttl_sec: Any) -> Any: ...
    @property
    def response_body(self: Any) -> Any: ...
    def response_body(self: Any, body: Any) -> Any: ...
    @property
    def session(self: Any) -> Any: ...
    def session_start(self: Any) -> Any: ...
    def session_destroy(self: Any) -> Any: ...
    @property
    def session_id(self: Any) -> Any: ...
    @property
    def jwt_payload(self: Any) -> Any: ...
    def jwt_generate(self: Any, payload: Any, secret: Any) -> Any: ...
    def set(self: Any, key: Any, value: Any) -> Any: ...
    def get(self: Any, key: Any) -> Any: ...
    @classmethod
    def create_test_context(cls: Any) -> Any: ...
    def free_test_context(self: Any) -> Any: ...
    def multipart_parse(self: Any, handler: Any) -> Any: ...
