from typing import Any, Callable, Dict, List, Optional, Union, Tuple, Type

class DBPool:
    def __init__(self: Any, driver_name: Any, dsn: Any) -> Any: ...
    def free(self: Any) -> Any: ...
    def __del__(self: Any) -> Any: ...
    def query(self: Any, sql: Any, params: Any) -> Any: ...
    def exec(self: Any, sql: Any) -> Any: ...
    @staticmethod
    def get_stats() -> Any: ...
