from typing import Any, Callable, Dict, List, Optional, Union, Tuple, Type

class Perm:
    @staticmethod
    def init() -> Any: ...
    @staticmethod
    def set_default(driver_name: Any) -> Any: ...
    @staticmethod
    def check(ctx: Any, permission: Any, resource: Any) -> Any: ...
    @staticmethod
    def require(ctx: Any, permission: Any, resource: Any) -> Any: ...
    @staticmethod
    def simple_init() -> Any: ...
    @staticmethod
    def simple_allow(role: Any, permission: Any, resource: Any) -> Any: ...
    @staticmethod
    def simple_clear() -> Any: ...
    @staticmethod
    def auto_middleware(ctx: Any) -> Any: ...
