from typing import Any, Callable, Dict, List, Optional, Union, Tuple, Type

class VectorDB:
    def __init__(self: Any, driver_name: Any, endpoint: Any, api_key: Any) -> Any: ...
    def __del__(self: Any) -> Any: ...
    def upsert(self: Any, collection: Any, points: Any) -> Any: ...
    def search(self: Any, collection: Any, vector: Any, limit: Any) -> Any: ...
