from typing import Any, Callable, Dict, List, Optional, Union, Tuple, Type

class WorkflowData:
    def __init__(self: Any, data_ptr: Any) -> Any: ...
    @property
    def type(self: Any) -> Any: ...
    @property
    def value(self: Any) -> Any: ...
    @property
    def meta(self: Any) -> Any: ...

class WorkflowContext:
    def __init__(self: Any, ctx_ptr: Any) -> Any: ...
    def strdup(self: Any, s: Any) -> Any: ...
    def data_new(self: Any, data_type: Any, value_ptr: Any) -> Any: ...
    def data_new_string(self: Any, value: Any, data_type: Any) -> Any: ...
    def alloc(self: Any, size: Any) -> Any: ...

class WorkflowNode:
    def __init__(self: Any, node_ptr: Any) -> Any: ...
    def set_entry(self: Any, is_entry: Any) -> Any: ...
    def set_join_policy(self: Any, policy: Any) -> Any: ...
    def set_interactive(self: Any, is_interactive: Any) -> Any: ...
    def set_schema(self: Any, schema_json: Any) -> Any: ...
    def set_timeout(self: Any, timeout_ms: Any) -> Any: ...
    def set_retry(self: Any, max_retries: Any, retry_delay_ms: Any) -> Any: ...
    def set_remote(self: Any, is_remote: Any) -> Any: ...
    def bind(self: Any, target_node: Any) -> Any: ...
    def on(self: Any, condition: Any, target_node: Any) -> Any: ...
    def on_loop(self: Any, condition: Any, target_node: Any) -> Any: ...
    def on_error(self: Any, target_node: Any) -> Any: ...
    def route(self: Any, router_fn: Any) -> Any: ...

class Workflow:
    def __init__(self: Any, name_or_ptr: Any) -> Any: ...
    def free(self: Any) -> Any: ...
    def __del__(self: Any) -> Any: ...
    @classmethod
    def register_handler(cls: Any, name: Any, handler_fn: Any) -> Any: ...
    @classmethod
    def load_yaml(cls: Any, path: Any) -> Any: ...
    @classmethod
    def from_json(cls: Any, json_str: Any) -> Any: ...
    @staticmethod
    def serve_ui(app: Any, path: Any) -> Any: ...
    def add(self: Any, node_id: Any, handler_fn: Any) -> Any: ...
    def add_ai(self: Any, node_id: Any, model: Any, system_msg: Any, prompt: Any, temperature: Any, max_tokens: Any, stream: Any, max_history_messages: Any) -> Any: ...
    def add_vector_search(self: Any, node_id: Any, ai_handle: Any, embedding_model: Any, db_handle: Any, collection: Any, limit: Any, input_template: Any) -> Any: ...
    def register_tool(self: Any, name: Any, description: Any, parameters_json: Any, tool_fn: Any) -> Any: ...
    def set_tool_discovery(self: Any, discovery_fn: Any) -> Any: ...
    def get_node(self: Any, node_id: Any) -> Any: ...
    def signal_continue(self: Any, exec_id: Any, input_data: Any, callback: Any) -> Any: ...
    def set_ttl(self: Any, ttl_sec: Any) -> Any: ...
    def set_budget(self: Any, max_tokens: Any) -> Any: ...
    def enable_distributed(self: Any, mq: Any) -> Any: ...
    def set_persistence(self: Any, wal_dir: Any) -> Any: ...
    def run(self: Any, input_val: Any, input_type: Any, callback: Any) -> Any: ...
    def resume(self: Any, exec_id: Any, callback: Any) -> Any: ...
    def run_traced(self: Any, input_val: Any, input_type: Any, callback: Any) -> Any: ...
    def trace_to_json(self: Any, trace_ptr: Any) -> Any: ...
    def trace_free(self: Any, trace_ptr: Any) -> Any: ...
    def to_mermaid(self: Any) -> Any: ...
    def _repr_html_(self: Any) -> Any: ...
    def register_monitor(self: Any, ctx: Any) -> Any: ...
