#!/usr/bin/env python3
"""
csilk SDK Generator — TypeScript and Python clients from OpenAPI spec.

Reads the OpenAPI 3.0 JSON from /openapi.json (or a file) and generates
a type-safe API client in TypeScript and/or Python.

Usage:
    python3 scripts/generate-sdk.py --url http://localhost:8080/openapi.json --output ./sdk
    python3 scripts/generate-sdk.py --file openapi.json --lang typescript --output ./sdk
    python3 scripts/generate-sdk.py --file openapi.json --lang both --output ./sdk
"""

import argparse
import json
import os
import re
import sys
import urllib.request
from datetime import datetime


class CodeGen:
    """Base code generator."""

    def __init__(self, spec: dict, base_url: str = "http://localhost:8080"):
        self.spec = spec
        self.base_url = base_url
        self.title = spec.get("info", {}).get("title", "API")
        self.version = spec.get("info", {}).get("version", "0.1.0")
        self.paths = spec.get("paths", {})

    @staticmethod
    def jsdoc_type(schema: dict) -> str:
        """Map OpenAPI schema type to TypeScript type."""
        if not schema:
            return "any"
        t = schema.get("type", "object")
        if t == "string":
            fmt = schema.get("format", "")
            return "string"
        if t == "integer":
            return "number"
        if t == "number":
            return "number"
        if t == "boolean":
            return "boolean"
        if t == "array":
            items = schema.get("items", {})
            return f"Array<{CodeGen.jsdoc_type(items)}>"
        if t == "object":
            return "Record<string, any>"
        return "any"

    @staticmethod
    def python_type(schema: dict) -> str:
        """Map OpenAPI schema type to Python type hint."""
        if not schema:
            return "Any"
        t = schema.get("type", "object")
        if t == "string":
            return "str"
        if t == "integer":
            return "int"
        if t == "number":
            return "float"
        if t == "boolean":
            return "bool"
        if t == "array":
            items = schema.get("items", {})
            return f"list[{CodeGen.python_type(items)}]"
        if t == "object":
            return "dict"
        return "Any"


class TypeScriptGen(CodeGen):
    """Generate TypeScript SDK."""

    def header(self) -> str:
        return f"""// Auto-generated by csilk SDK Generator
// Source: {self.title} v{self.version}
// Generated: {datetime.utcnow().isoformat()}

export interface RequestConfig {{
    baseUrl?: string;
    headers?: Record<string, string>;
}}

export class ApiError extends Error {{
    constructor(
        public status: number,
        public body: string,
    ) {{
        super(`HTTP ${{status}}: ${{body}}`);
    }}
}}

export class ApiClient {{
    private baseUrl: string;
    private headers: Record<string, string>;

    constructor(config: RequestConfig = {{}}) {{
        this.baseUrl = config.baseUrl || '{self.base_url}';
        this.headers = {{ 'Content-Type': 'application/json', ...config.headers }};
    }}

    private async request<T>(
        method: string,
        path: string,
        body?: unknown,
        query?: Record<string, string>,
    ): Promise<T> {{
        let url = this.baseUrl + path;
        if (query) {{
            const params = new URLSearchParams(query).toString();
            if (params) url += '?' + params;
        }}
        const res = await fetch(url, {{
            method,
            headers: this.headers,
            body: body ? JSON.stringify(body) : undefined,
        }});
        if (!res.ok) {{
            throw new ApiError(res.status, await res.text());
        }}
        const text = await res.text();
        try {{
            return JSON.parse(text) as T;
        }} catch {{
            return text as unknown as T;
        }}
    }}
"""

    def generate(self) -> str:
        lines = [self.header()]
        methods = []

        for path, methods_spec in sorted(self.paths.items()):
            for method, op in methods_spec.items():
                if method.lower() not in ("get", "post", "put", "delete", "patch"):
                    continue
                func_name = self._func_name(method, path)
                ts_method = method.upper()
                req_body = self._request_body(op)
                resp_type = self._response_type(op)
                param_inputs = self._path_params(path)
                query_params = self._query_params(op)
                method_doc = op.get("summary", "")

                args = []
                if param_inputs:
                    for p in param_inputs:
                        args.append(f"{p}: string")
                if req_body:
                    args.append(f"body: {req_body}")
                if query_params:
                    args.append("query?: Record<string, string>")

                lines.append(self._render_method(
                    func_name, ts_method, path, args, param_inputs,
                    query_params, resp_type, method_doc
                ))
                methods.append(func_name)

        lines.append("}")
        return "\n".join(lines)

    def _func_name(self, method: str, path: str) -> str:
        """Generate camelCase function name from method + path."""
        clean = path.replace("{", "").replace("}", "").replace("/", "_").strip("_")
        if not clean:
            clean = "index"
        clean = re.sub(r'[^a-zA-Z0-9_]', '_', clean)
        parts = clean.split("_")
        if len(parts) > 1:
            clean = parts[0] + "".join(p.capitalize() for p in parts[1:])
        return clean

    def _path_params(self, path: str) -> list:
        """Extract path parameter names."""
        return re.findall(r'\{(\w+)\}', path)

    def _query_params(self, op: dict) -> list:
        """Extract query parameter names from operation parameters."""
        params = []
        for p in op.get("parameters", []):
            if p.get("in") == "query":
                params.append(p["name"])
        return params

    def _request_body(self, op: dict) -> str | None:
        """Extract request body schema reference."""
        rb = op.get("requestBody", {})
        content = rb.get("content", {}).get("application/json", {})
        schema = content.get("schema", {})
        ref = schema.get("$ref", "")
        if ref:
            name = ref.split("/")[-1]
            return name
        return None if not schema else self.jsdoc_type(schema)

    def _response_type(self, op: dict) -> str:
        """Determine response type from 200-299 responses."""
        for code in ("200", "201"):
            resp = op.get("responses", {}).get(code, {})
            content = resp.get("content", {}).get("application/json", {})
            schema = content.get("schema", {})
            ref = schema.get("$ref", "")
            if ref:
                name = ref.split("/")[-1]
                return name
            if schema:
                return self.jsdoc_type(schema)
        return "any"

    def _render_method(self, name, method, path, args, params,
                        query_params, resp_type, doc):
        """Render a single API method."""
        quoted_path = path
        for p in params:
            quoted_path = quoted_path.replace(f"{{{p}}}", f"${{{p}}}")

        args_str = ", ".join(args) if args else ""
        sig = f"    async {name}({args_str}): Promise<{resp_type}> {{"

        body = f'        return this.request<{resp_type}>("{method}", `{quoted_path}`'
        if any(a.startswith("body:") for a in args):
            body += ", body"
        else:
            body += ", undefined"
        if query_params:
            body += ", query"
        body += ");"

        doc_line = f"    /** {doc} */" if doc else ""
        return f"{doc_line}\n{sig}\n{body}\n    }}\n"


class PythonGen(CodeGen):
    """Generate Python SDK."""

    def header(self) -> str:
        return f'''"""Auto-generated by csilk SDK Generator
Source: {self.title} v{self.version}
Generated: {datetime.utcnow().isoformat()}
"""

from __future__ import annotations
import json
from typing import Any, Optional
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote
from urllib.error import HTTPError


class ApiError(Exception):
    """HTTP API error."""
    def __init__(self, status: int, body: str):
        self.status = status
        self.body = body
        super().__init__(f"HTTP {{status}}: {{body}}")


class ApiClient:
    """Generated API client."""
    def __init__(self, base_url: str = "{self.base_url}", headers: dict | None = None):
        self.base_url = base_url.rstrip("/")
        self.headers = {{"Content-Type": "application/json", **(headers or {{}})}}

    def _request(self, method: str, path: str,
                  body: Any = None, query: dict | None = None) -> Any:
        url = self.base_url + path
        if query:
            url += "?" + urlencode(query)
        data = json.dumps(body).encode() if body is not None else None
        req = Request(url, data=data, headers=self.headers, method=method)
        try:
            with urlopen(req) as res:
                text = res.read().decode()
                try:
                    return json.loads(text)
                except json.JSONDecodeError:
                    return text
        except HTTPError as e:
            raise ApiError(e.code, e.read().decode()) from e
'''

    def generate(self) -> str:
        lines = [self.header()]
        methods = []

        for path, methods_spec in sorted(self.paths.items()):
            for method, op in methods_spec.items():
                if method.lower() not in ("get", "post", "put", "delete", "patch"):
                    continue
                func_name = self._func_name(method, path)
                py_method = method.upper()
                req_body = self._request_body(op)
                resp_type = self._response_type(op)
                param_inputs = self._path_params(path)
                query_params = self._query_params(op)
                method_doc = op.get("summary", "")

                args = ["self"]
                if param_inputs:
                    for p in param_inputs:
                        args.append(f"{p}: str")
                if req_body:
                    args.append(f"body: {req_body}")
                if query_params:
                    args.append("query: dict | None = None")

                lines.append(self._render_method(
                    func_name, py_method, path, args, param_inputs,
                    query_params, resp_type, method_doc
                ))
                methods.append(func_name)

        return "\n".join(lines)

    def _func_name(self, method: str, path: str) -> str:
        clean = path.replace("{", "").replace("}", "").replace("/", "_").strip("_")
        if not clean:
            clean = "index"
        clean = re.sub(r'[^a-zA-Z0-9_]', '_', clean)
        return clean

    def _path_params(self, path: str) -> list:
        return re.findall(r'\{(\w+)\}', path)

    def _query_params(self, op: dict) -> list:
        params = []
        for p in op.get("parameters", []):
            if p.get("in") == "query":
                params.append(p["name"])
        return params

    def _request_body(self, op: dict) -> str | None:
        rb = op.get("requestBody", {})
        content = rb.get("content", {}).get("application/json", {})
        schema = content.get("schema", {})
        ref = schema.get("$ref", "")
        if ref:
            return ref.split("/")[-1]
        return None if not schema else self.python_type(schema)

    def _response_type(self, op: dict) -> str:
        for code in ("200", "201"):
            resp = op.get("responses", {}).get(code, {})
            content = resp.get("content", {}).get("application/json", {})
            schema = content.get("schema", {})
            ref = schema.get("$ref", "")
            if ref:
                return ref.split("/")[-1]
            if schema:
                return self.python_type(schema)
        return "Any"

    def _render_method(self, name, method, path, args, params,
                        query_params, resp_type, doc):
        args_str = ", ".join(args)
        quoted_path = path
        for p in params:
            quoted_path = quoted_path.replace(f"{{{p}}}", f"{{{p}}}")

        safe_path = path
        for p in params:
            safe_path = safe_path.replace(f"{{{p}}}", f"{{quote({p}, safe='')}}")
        path_expr = f'f"{safe_path}"'

        call_args = f'"{method}", {path_expr}'
        if any(a.startswith("body:") for a in args):
            call_args += ", body"
        if query_params:
            call_args += ", query"

        sig = f"    def {name}({args_str}) -> {resp_type}:"
        doc_line = f'        """{doc}"""' if doc else ""
        return f"{sig}\n{doc_line}\n        return self._request({call_args})\n"


def main():
    parser = argparse.ArgumentParser(description="csilk SDK Generator")
    parser.add_argument("--url", help="URL of OpenAPI JSON endpoint")
    parser.add_argument("--file", help="Path to OpenAPI JSON file")
    parser.add_argument("--lang", default="both", choices=["typescript", "python", "both"])
    parser.add_argument("--output", default="./sdk", help="Output directory")
    args = parser.parse_args()

    spec = None
    if args.file:
        with open(args.file) as f:
            spec = json.load(f)
    elif args.url:
        with urllib.request.urlopen(args.url) as res:
            spec = json.loads(res.read().decode())
    else:
        parser.error("Either --url or --file is required")

    os.makedirs(args.output, exist_ok=True)

    base_url = "http://localhost:8080"
    if args.url:
        base_url = args.url.rsplit("/openapi.json", 1)[0]

    if args.lang in ("typescript", "both"):
        gen = TypeScriptGen(spec, base_url)
        content = gen.generate()
        out_file = os.path.join(args.output, "api-client.ts")
        with open(out_file, "w") as f:
            f.write(content)
        print(f"Generated TypeScript SDK: {out_file} ({len(content)} bytes)")

    if args.lang in ("python", "both"):
        gen = PythonGen(spec, base_url)
        content = gen.generate()
        out_file = os.path.join(args.output, "api_client.py")
        with open(out_file, "w") as f:
            f.write(content)
        print(f"Generated Python SDK: {out_file} ({len(content)} bytes)")


if __name__ == "__main__":
    main()
