# cmake/dependencies.cmake — FetchContent and find_package for all dependencies

include(FetchContent)

if(CSILK_USE_URING)
  message(STATUS "io_uring backend selected — fetching liburing")
  set(CSILK_USE_URING_ONLY TRUE)
  FetchContent_Declare(
    liburing
    GIT_REPOSITORY https://github.com/axboe/liburing.git
    GIT_TAG        liburing-2.5
  )
  FetchContent_MakeAvailable(liburing)
  if(liburing_SOURCE_DIR AND liburing_BINARY_DIR)
    set(LIBURING_GEN_DIR "${liburing_BINARY_DIR}/src/include/liburing")
    file(MAKE_DIRECTORY "${LIBURING_GEN_DIR}")
    file(WRITE "${LIBURING_GEN_DIR}/compat.h"
"/* SPDX-License-Identifier: MIT */
#ifndef LIBURING_COMPAT_H
#define LIBURING_COMPAT_H

/* generated by csilk CMakeLists.txt for liburing v2.5 */

#include <linux/openat2.h>   /* struct open_how (Linux >= 5.6) */

#if defined(__has_include)
#  if __has_include(\"linux/time_types.h\")
#    include <linux/time_types.h>
#  else
struct __kernel_timespec {
    int64_t tv_sec;
    long long tv_nsec;
};
#  endif
#endif

#endif /* LIBURING_COMPAT_H */
")
    file(WRITE "${LIBURING_GEN_DIR}/io_uring_version.h"
"/* SPDX-License-Identifier: MIT */
#ifndef LIBURING_VERSION_H
#define LIBURING_VERSION_H

/* generated by csilk CMakeLists.txt for liburing v2.5 */

#define IO_URING_VERSION_MAJOR 2
#define IO_URING_VERSION_MINOR 5

#endif /* LIBURING_VERSION_H */
")

    include_directories(${liburing_SOURCE_DIR}/src/include)
    include_directories(${liburing_BINARY_DIR}/src/include)
    include_directories(${liburing_SOURCE_DIR}/src)

    set(LIBURING_SOURCES
      "${liburing_SOURCE_DIR}/src/queue.c"
      "${liburing_SOURCE_DIR}/src/setup.c"
      "${liburing_SOURCE_DIR}/src/syscall.c"
      "${liburing_SOURCE_DIR}/src/register.c"
      "${liburing_SOURCE_DIR}/src/ffi.c"
      "${liburing_SOURCE_DIR}/src/version.c"
    )
    add_library(uring STATIC ${LIBURING_SOURCES})
    target_include_directories(uring PRIVATE
      "${liburing_SOURCE_DIR}/src/include"
      "${liburing_BINARY_DIR}/src/include"
    )
    target_compile_definitions(uring PRIVATE -D_GNU_SOURCE)
  endif()
else()
  find_library(LIBUV_LIB NAMES uv)
  find_path(LIBUV_INCLUDE_DIR uv.h)
  if(LIBUV_LIB AND LIBUV_INCLUDE_DIR)
    message(STATUS "Found system libuv: ${LIBUV_LIB}")
    set(libuv_LIBRARIES ${LIBUV_LIB})
    include_directories(${LIBUV_INCLUDE_DIR})
  else()
    message(FATAL_ERROR "libuv not found on system. Please install libuv-dev.")
  endif()
endif()

# Prefer system llhttp; fallback to FetchContent from source
find_library(LLHTTP_LIB NAMES llhttp libllhttp)
if(NOT LLHTTP_LIB)
  message(STATUS "System llhttp not found — fetching from source")
  FetchContent_Declare(
    llhttp
    GIT_REPOSITORY https://github.com/nodejs/llhttp.git
    GIT_TAG        release/v9.4.1
  )
  set(LLHTTP_BUILD_STATIC_LIBS ON)
  FetchContent_MakeAvailable(llhttp)
  set(LLHTTP_LIB llhttp::llhttp)
  if(llhttp_SOURCE_DIR)
    include_directories(${llhttp_SOURCE_DIR}/include)
  endif()
else()
  message(STATUS "Found system llhttp: ${LLHTTP_LIB}")
endif()

# Fetch yyjson (header-only JSON library)
FetchContent_Declare(
  yyjson
  GIT_REPOSITORY https://github.com/ibireme/yyjson.git
  GIT_TAG        0.12.0
)
FetchContent_MakeAvailable(yyjson)

# Fetch nghttp2
set(ENABLE_LIB_ONLY ON CACHE BOOL "" FORCE)
set(ENABLE_SHARED_LIB OFF CACHE BOOL "" FORCE)
set(ENABLE_STATIC_LIB ON CACHE BOOL "" FORCE)
set(ENABLE_EXAMPLES OFF CACHE BOOL "" FORCE)
set(ENABLE_TESTS OFF CACHE BOOL "" FORCE)
FetchContent_Declare(
  nghttp2
  GIT_REPOSITORY https://github.com/nghttp2/nghttp2.git
  GIT_TAG        v1.61.0
)
FetchContent_MakeAvailable(nghttp2)
if(nghttp2_SOURCE_DIR)
  include_directories(${nghttp2_SOURCE_DIR}/lib/includes)
  include_directories(${nghttp2_BINARY_DIR}/lib/includes)
endif()

# Find CURL (HTTP/2 support via nghttp2)
find_package(CURL REQUIRED)

include_directories(include)
include_directories(src)
include_directories(${CMAKE_CURRENT_BINARY_DIR}/include)
include_directories(${yyjson_SOURCE_DIR})
include_directories(${CURL_INCLUDE_DIRS})

# Generate version.h into the binary include/ tree (mirroring the source
# include/ layout) so consumers of the csilk target — add_subdirectory,
# FetchContent, and installed packages alike — can resolve "csilk/version.h".
configure_file(
  include/csilk/version.h.in
  ${CMAKE_CURRENT_BINARY_DIR}/include/csilk/version.h
  @ONLY
)
configure_file(
  python/csilk/_version.py.in
  ${CMAKE_CURRENT_SOURCE_DIR}/python/csilk/_version.py
  @ONLY
)

# Find MySQL (optional)
find_library(MYSQL_LIB NAMES mysqlclient libmysqlclient)
if(MYSQL_LIB)
  message(STATUS "Found MySQL client library: ${MYSQL_LIB}")
  find_path(MYSQL_INCLUDE_DIR mysql.h PATHS /usr/include/mysql /usr/local/include/mysql)
  if(MYSQL_INCLUDE_DIR)
    include_directories(${MYSQL_INCLUDE_DIR})
    message(STATUS "Found MySQL include dir: ${MYSQL_INCLUDE_DIR}")
  endif()
else()
  message(STATUS "MySQL client library not found — mysql driver will not build")
endif()

# Find PostgreSQL (optional)
find_library(PQ_LIB NAMES pq libpq)
if(PQ_LIB)
  message(STATUS "Found PostgreSQL client library: ${PQ_LIB}")
  find_path(PQ_INCLUDE_DIR libpq-fe.h PATHS /usr/include/postgresql /usr/local/include/postgresql)
  if(PQ_INCLUDE_DIR)
    include_directories(${PQ_INCLUDE_DIR})
    message(STATUS "Found PostgreSQL include dir: ${PQ_INCLUDE_DIR}")
  endif()
else()
  message(STATUS "PostgreSQL client library not found — postgres driver will not build")
endif()

# Find MongoDB (optional)
find_library(MONGOC_LIB NAMES mongoc-1.0)
find_library(BSON_LIB NAMES bson-1.0)
if(MONGOC_LIB AND BSON_LIB)
  message(STATUS "Found MongoDB client library: ${MONGOC_LIB}")
  find_path(MONGOC_INCLUDE_DIR mongoc/mongoc.h PATHS /usr/include/libmongoc-1.0 /usr/local/include/libmongoc-1.0)
  find_path(BSON_INCLUDE_DIR bson/bson.h PATHS /usr/include/libbson-1.0 /usr/local/include/libbson-1.0)
  if(MONGOC_INCLUDE_DIR AND BSON_INCLUDE_DIR)
    include_directories(${MONGOC_INCLUDE_DIR})
    include_directories(${BSON_INCLUDE_DIR})
    message(STATUS "Found MongoDB include dir: ${MONGOC_INCLUDE_DIR}")
    set(HAS_MONGODB TRUE)
  endif()
else()
  message(STATUS "MongoDB client library not found — mongodb driver will not build")
endif()

# Find Redis (hiredis) (optional)
find_library(HIREDIS_LIB NAMES hiredis)
if(HIREDIS_LIB)
  message(STATUS "Found hiredis library: ${HIREDIS_LIB}")
  find_path(HIREDIS_INCLUDE_DIR hiredis/hiredis.h PATHS /usr/include /usr/local/include)
  if(HIREDIS_INCLUDE_DIR)
    include_directories(${HIREDIS_INCLUDE_DIR})
    message(STATUS "Found hiredis include dir: ${HIREDIS_INCLUDE_DIR}")
  endif()
else()
  message(STATUS "hiredis library not found — redis driver will not build")
endif()

set(THREADS_PREFER_PTHREAD_FLAG ON)
find_package(Threads REQUIRED)

# Find system libyaml (>= 0.2.0)
find_package(PkgConfig QUIET)
if(PKG_CONFIG_FOUND)
  pkg_check_modules(YAML QUIET yaml>=0.2.0)
endif()
if(NOT YAML_FOUND)
  find_library(YAML_LIB NAMES yaml libyaml)
  find_path(YAML_INCLUDE_DIR yaml.h PATH_SUFFIXES yaml)
  if(YAML_LIB AND YAML_INCLUDE_DIR)
    set(YAML_FOUND TRUE)
    set(YAML_LIBRARIES ${YAML_LIB})
    set(YAML_INCLUDE_DIRS ${YAML_INCLUDE_DIR})
  endif()
endif()
if(NOT YAML_FOUND)
  message(FATAL_ERROR "libyaml >= 0.2.0 not found. Install libyaml-dev.\n"
    "  Debian/Ubuntu: sudo apt install libyaml-dev\n"
    "  macOS: brew install libyaml")
endif()
message(STATUS "Found libyaml: ${YAML_LIBRARIES}")

# Find system zlib (>= 1.2.0)
find_package(ZLIB 1.2 REQUIRED)
message(STATUS "Found zlib: ${ZLIB_VERSION_STRING}")

# Find system sqlite3 (>= 3.20.0)
find_package(SQLite3 3.20 REQUIRED)
message(STATUS "Found sqlite3: ${SQLite3_VERSION}")

# Find OpenSSL (>= 1.1.1 for TLS 1.3)
find_package(OpenSSL 1.1.1 REQUIRED)
message(STATUS "Found OpenSSL: ${OPENSSL_VERSION}")
