name: Build Wheels

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v5
      
      # We need ninja and cmake installed
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          
      - name: Install cibuildwheel
        run: python -m pip install --upgrade cibuildwheel
        
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        env:
          HOMEBREW_NO_REQUIRE_TAP_TRUST: 1
        run: brew install cmake pkg-config llvm libyaml zlib curl openssl libpq sqlite3 libuv

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
          CIBW_SKIP: "*-musllinux_*"
          CIBW_ARCHS_MACOS: "arm64"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux_2_34_x86_64
          CIBW_BEFORE_ALL_LINUX: >
            yum install -y
            openssl-devel
            libyaml-devel
            libcurl-devel
            zlib-devel
            sqlite-devel
            libuv-devel
            pkgconfig
          
      - uses: actions/upload-artifact@v5
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build SDist
        run: pipx run build --sdist
      - uses: actions/upload-artifact@v5
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
